import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next JS, Todo-List',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<meta
				name="google-site-verification"
				content="G9BhUCe0bmundARnIADRTjOorNKfAWHFwWGi1sdko2Y"
			/>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
